apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: appgtw-identity
spec:
  type: 0
  ResourceID: "/subscriptions/{subscriptionid}/resourcegroups/{vmagentpool_resourceid}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{managedidentityname}"
  ClientID: {clientid}

---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: azure-identity-binding
spec:
  AzureIdentity: {managedidentityname}
  Selector: appgtw